### ISSUE TITLE
pull request from templater

### ISSUE THREAD

**Issue by steveoh** [agrc/templater#7]
how possible would it be to create the pull request from the templater to remove the copy pasting?

@jpechmann was asking for a way to make it easier for people to contribute.

**Comment by stdavis** [comment]
I'm not sure. I'm guessing that it's possible. They'd have to authenticate with GitHub. Not sure how to handle the adding of new files, etc.

**Comment by stdavis** [comment]
I'm not sure that this is helpful anymore since most are familiar with the PR process.
